name: build-linux

on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.cpp"
      - "**/*.c"
      - "**/*.hpp"
      - "**/*.h"
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: install base dependencies
      run: sudo apt update && sudo apt install build-essential wget tar libgl1-mesa-dev libx11-dev libxcursor-dev cmake pkg-config git -y

    - name: install allegro font & image dependencies
      run: sudo apt install libfreetype-dev libpng-dev libjpeg-dev libfreeimage-dev -y

    - name: install allegro sound & video dependencies
      run: sudo apt install libdumb1-dev libflac-dev libogg-dev libvorbis-dev libopusfile-dev libtheora-dev libwebp-dev -y

    - name: download minimp3 support
      run: wget https://raw.githubusercontent.com/lieff/minimp3/refs/heads/master/minimp3.h && wget https://raw.githubusercontent.com/lieff/minimp3/refs/heads/master/minimp3_ex.h && sudo mv minimp3.h /usr/local/include && sudo mv minimp3_ex.h /usr/local/include

    - name: install allegro other dependencies
      run: sudo apt install libphysfs-dev libsdl2-dev libgtk-3-dev -y

    - name: download allegro-5.2.7.0
      run: wget https://github.com/liballeg/allegro5/releases/download/5.2.7.0/allegro-5.2.7.0.tar.gz

    - name: unzip allegro-5.2.7.0
      run: tar -xzf allegro-5.2.7.0.tar.gz

    - name: build allegro-5.2.7.0
      run: cd allegro-5.2.7.0 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DWANT_PKG_CONFIG=ON -DWANT_SHARED=ON .. && make -j8 && sudo make install && sudo ldconfig /usr/local/lib

    - uses: actions/checkout@v4
      with:
        path: SourceCode

    - name: build
      run: cd SourceCode && make

    - name: check build
      run: ls SourceCode/game

    - name: run test mode
      run: SourceCode/game --test
